### ISSUE TITLE
Referencing - Add details of IEEE Reference Style

### ISSUE THREAD

**Issue by alpesh-rama** [alpesh-rama/practical-introduction-to-machine-learning#1]
- [x] Create a markdown (.md) document explaining how to reference using in the IEEE (Institute of Electrical and Electronics Engineers) style.
- [x] Create a link to this file within the `Quality` section of the main Readme.

**Comment by Ishika414** [comment]
I would like to work on this issue. Please assign this to me

**Comment by alpesh-rama** [comment]
Welcome onboard @Ishika414! Have at it 😃

**Comment by Ishika414** [comment]
@alpesh-rama Thank you for the opportunity. I have created the pull request for this issue

**Comment by alpesh-rama** [comment]
Issue successfully completed by @Ishika414
